includes: projects/task/ft.yaml
dataset:
  meta_processor: RWTHFSMetaProcessor
  video_processor: RWTHFSVideoProcessor
  text_processor: TextProcessor
  test_path: data/rwthfs/test.txt
  val_path: data/rwthfs/val.txt
  train_path: data/rwthfs/train.txt
  gesture_id_path: data/rwthfs/gesture_ids.txt
  vfeat_dir: data/feat/feat_rwthfs_s3d
  aligner: DSAligner
  max_video_len: 8
  max_len: 32
  # num_iso_layer: 12
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: 
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 6
loss:
  # loss_cls: V2TContraLoss
  loss_cls: MMContraLoss
fairseq:
  dataset:
    batch_size: 35
    num_workers: 1
  optimization:
    max_epoch: 10
  checkpoint:
    save_dir: runs/retri/videoclip/rwthfs
 
